### PR TITLE
Minor markup fixes for a11y

### PR DESCRIPTION
**Pull request by surma**
[TIL](https://twitter.com/DasSurma/status/834713623851302912) that the `lang` attribute on `<html>` is important, so I fixed that.

I also did a pass with a screen reader on the current site and noticed that demo feels awkward. Tried to improve it, please double-check I’m not doing anything dumb here, @robdodson 😅 

The code section feels awkward, too, but I’m not sure how to address that.

### CODE REVIEW

**Comment by robdodson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robdodson** [comment]
+1 for `lang` fixes.

I don't think we can use the `section` role as the ARIA spec recommends against directly using abstract roles (https://www.w3.org/TR/wai-aria-1.1/#abstract_roles). Let's go with `region` instead.

Also looks like we have a duplicate id on each page, for example:

`<ul class="literate demo" id="dash-tabs">` got called out by axe so somewhere else there's a `dash-tabs` id.

Also we have 200+ low contrast text warnings 😨

**Comment by surma** [comment]
> Also we have 200+ low contrast text warnings 😨

Yeah, I am aware. I was thinking of addressing those when we have the logo and have to figure out a page design :)

**Comment by robdodson** [comment]
> Yeah, I am aware. I was thinking of addressing those when we have the logo and have to figure out a page design :)

sgtm

**Pull request merged**
